Auto-Merge abort and better error detection
nekudo/shiny_deploy pull request #13
Opened 2023-10-13 16:00 UTC by jraucademy

Resets an auto-merge, if the deployment had an error and the git status is hanging in an active merge (by unresolved conflicts). 
We do this in the beginning of a deployment and after completing the repo-tasks to be safe being always on a working branch/repo after a deployment, even if there was an error.

2023-10-16 11:58 UTC, yroak reviewed
Sieht soweit alles gut aus. Ich würde aber grundsätzlich Call by Reference nur verwenden, wenn es wirklich nötig ist.

2023-10-16 11:58 UTC, yroak commented on src/ShinyDeploy/Domain/Deployment.php
> +        if ($isRepoStatusCorrupted) {
```suggestion
        $isRepoStatusCorrupted = this->checkRepoStatus();
        if ($isRepoStatusCorrupted === false) {
            $this->logResponder->error('Repository status check failed. Aborting job.');
            return false;
        }

        if ($isRepoStatusCorrupted) {
```

2023-10-16 11:58 UTC, yroak commented on src/ShinyDeploy/Domain/Deployment.php
> +            $this->checkRepoStatus($isRepoStatusCorrupted);
```suggestion
            $isRepoStatusCorrupted = this->checkRepoStatus();
```

2023-10-16 11:58 UTC, yroak commented on src/ShinyDeploy/Domain/Repository.php
> +        return true;
```suggestion
    public function checkRepoStatus(): bool
    {
        return $this->git->isMergeInProgress();
```

2023-10-16 11:58 UTC, yroak commented on src/ShinyDeploy/Domain/Repository.php
> +        return true;
Call by reference ist hier nicht wirklich nötig, denke ich.

2023-10-16 11:58 UTC, yroak commented on src/ShinyDeploy/Domain/Deployment.php
> +        return $this->repository->checkRepoStatus($isRepoCorrupted);
```suggestion
    protected function checkRepoStatus(): bool
    {
        return $this->repository->checkRepoStatus();
```

2023-10-16 12:36 UTC, yroak approved these changes

2023-10-17 12:20 UTC, nekudo requested changes

2023-10-17 12:20 UTC, nekudo commented on src/ShinyDeploy/Domain/Deployment.php
> +        if ($this->checkRepoStatusIsCorrupted()) {
Please rename method according to naming conversions to "repoStatusIsCurrupted".

2023-10-17 12:20 UTC, nekudo commented on src/ShinyDeploy/Domain/Deployment.php
> +            $this->logResponder->log('Reset corrupted repository status by resetting...');
Please change message to. "Corrupted repository detected. Trying to reset...".

2023-10-17 12:20 UTC, nekudo commented on src/ShinyDeploy/Domain/Deployment.php
> +                $this->logResponder->error('Repository status reset failed. Aborting job.');
Please change message to "Could not reset corrupted repository. Aborting job.".

2023-10-17 12:20 UTC, nekudo commented on src/ShinyDeploy/Domain/Deployment.php
> +            $isRepoStatusCorrupted = $this->checkRepoStatusIsCorrupted();
Why is the repository check (and possible reset) executed a second time at this point?

2023-10-17 12:20 UTC, nekudo commented on src/ShinyDeploy/Domain/Deployment.php
> +    protected function forcedAutoMerge(string $localRevision): bool
It seems this method is never used/called?

2023-10-18 07:51 UTC, jraucademy commented on src/ShinyDeploy/Domain/Deployment.php
> +            $isRepoStatusCorrupted = $this->checkRepoStatusIsCorrupted();
We want to exit this process with a clean git status for being able to trigger other actions afterwards. We also do this check in the beginning of the deploy-action, because it also could be, that the git status was corrupted before. In fact we are checking the git status when entering the deployment, and also when leaving to make sure, that in between everything worked well and we reached a status we can proceed on.

2023-10-18 08:01 UTC, jraucademy commented on src/ShinyDeploy/Domain/Deployment.php
> +    protected function forcedAutoMerge(string $localRevision): bool
Now it is ;-)

2023-10-18 09:21 UTC, yroak approved these changes

2023-10-18 09:22 UTC, merged